---
# tasks file for Nainterceptor.haproxy
-   name: "Install haproxy"
    yum: name=haproxy state=present
    tags: haproxy
    notify:
        - Enable haproxy

-   name: "Configure haproxy"
    template: src=../files/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    tags: haproxy
    notify:
        - Restart haproxy